### ISSUE TITLE
what is the param "embedding_manager_ckpt" in main.py

### ISSUE THREAD

**Issue by carvychen** [zyxElsa/ProSpect#7]
<img width="1179" alt="image" src="https://github.com/zyxElsa/ProSpect/assets/30137344/f22eef17-6cf1-41b5-bedc-a4b8eeb238b2">
After I run the main.py with your suggestion, I meet this error. How can I fix it?

**Comment by Magauiya** [comment]
@carvychen how did you solve this problem?

**Comment by carvychen** [comment]
[This](https://github.com/zyxElsa/ProSpect/issues/4) might be helpful.
